sudo: required
dist: trusty
language: node_js
node_js:
  - '6.9'

env:
  global:
  - ENCRYPTION_LABEL: "e8dbd5618212"
  - COMMIT_AUTHOR_EMAIL: "nadapapa@gmail.com"

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
srcclr:
    debug: true

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g angular-cli
- npm install
- ng build

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash ./gh-deploy.sh

script: npm run test
